### ISSUE TITLE
Fix text

### ISSUE THREAD

**Issue by AsLogd** [rLoopTeam/website-v5#1]
- [x] Use same font as the design
- [x] Use same font sizes for every section as the design
- [x] Separate the text in paragraphs so it matches the design

**Comment by AAgar** [comment]
If the circles are of varying sizes, then should the fonts be the same size for everything? I tried it out and it looks odd because some circles are nearly filled and others are not even half filled. It makes sense if there is a lot more text in a larger circle, but the proportions are off.

**Comment by AsLogd** [comment]
With same I meant same as the design, not same between them. sorry
