### ISSUE TITLE
Favicon wrong path

### ISSUE THREAD

**Issue by AsLogd** [rLoopTeam/website-v5#13]
All links from index.html should point to dist folder

**Comment by AAgar** [comment]
Why wouldn't we keep the favicon in the images folder? If it is in images then isn't the path correct?

**Comment by AsLogd** [comment]
Yes, it should be in images folder. But index is pointing to src/. Only dist/ folder will be served, so there is no acces from index to src/.
Images should be in src/images, but index should point to dist/assets/img (when creating a distribution, images are optimized and copied to that folder)
