### ISSUE TITLE
Connect "The Problem" line to traffic image

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v5#36]
There is a slight gap in line from "The Problem" bubble to the image of the traffic.
![capture](https://cloud.githubusercontent.com/assets/13357722/25665629/32585ad4-2fec-11e7-966e-718bfecf2620.JPG)

**Comment by AsLogd** [comment]
In this case we could argue that this is a "bug". "enhancement" label should be used for non-critical enhancements (or future features). For general problems no label is ok

**Comment by brentenebros** [comment]
roger that, thanks @AsLogd
