### ISSUE TITLE
Add Digi-Key to Sponsor List Page, Immediately below TE Connectivity

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v5#77]
Digi-Key logo attached below, also available at: https://drive.google.com/open?id=0B5CvmK-zagQgcXIxN25neDZEbEU

**Description:**

> Digi-Key is the fourth largest electronic component distributor in North America, and fifth largest in the world. Digi-Key serves design engineers and the prototyping market, as well as an expanding role in supplying production quantities for OEMs and contract manufacturers.

![digikeylogo 1](https://user-images.githubusercontent.com/13357722/28829755-d8fa6cc2-76a2-11e7-8076-c5d689313c6a.jpg)

**Comment by AsLogd** [comment]
something is wrong with this image. Once downloaded I can't open it. I'll make an screenshot for now
